export const ROLE_IMAGES: Record<string, string> = {
    "Software Engineer": "/sw_eng.png",
    "Product Manager": "/pm.png",
    "Data Analyst": "/data_analyst.png",
    "UX Designer": "/ux_designer.png",
    "Digital Marketer": "/digital_marketer.png",
    "IT Support Specialist": "/it_support.png",
    "Cybersecurity Analyst": "/cybersec_analyst.png",
    "DevOps Engineer": "/devops_eng.png",
    "QA Engineer": "/qa_eng.png",
    "Retail Sales Associate": "/retail_assoc.png",
    "Cashier": "/cashier.png",
    "Home Health Aide": "/home_health_aide.png",
    "Warehouse Associate": "/warehouse_assoc.png",
    "Food Preparation Worker": "/food_prep.png",
    "Customer Service Rep": "/csr.png",
    "Stock Clerk": "/stock_clerk.png",
    "Janitor / Custodian": "/custodian.png",
    "Packer / Packager": "/packer.png"
};

export const ROLE_ICONS: Record<string, string> = {
    "Software Engineer": "/sw_eng_icon.png",
    "Product Manager": "/pm_icon.png",
    "Data Analyst": "/data_analyst_icon.png",
    "UX Designer": "/ux_designer_icon.png",
    "Digital Marketer": "/digital_marketer_icon.png",
    "IT Support Specialist": "/it_support_icon.png",
    "Cybersecurity Analyst": "/cybersec_analyst_icon.png",
    "DevOps Engineer": "/devops_eng_icon.png",
    "QA Engineer": "/qa_eng_icon.png",
    "Retail Sales Associate": "/retail_assoc_icon.png",
    "Cashier": "/cashier_icon.png",
    "Home Health Aide": "/home_health_aide_icon.png",
    "Warehouse Associate": "/warehouse_assoc_icon.png",
    "Food Preparation Worker": "/food_prep_icon.png",
    "Customer Service Rep": "/csr_icon.png",
    "Stock Clerk": "/stock_clerk_icon.png",
    "Janitor / Custodian": "/custodian_icon.png",
    "Packer / Packager": "/packer_icon.png"
};
